#!/bin/bash
# Regenerates the vendored three.js addon bundles (scripts/external/three/*.js)
# from upstream examples/jsm and npm addon packages, with `three` aliased to
# the global THREE defined by the core prebundle (see build-three.sh).
# Run manually after upgrading three or the addon packages (npm run build:addons).
set -e
cd "$(dirname "$0")/.."

THREEVER=$(node -pe "JSON.parse(require('fs').readFileSync('node_modules/three/package.json', 'utf8')).version")
SHIM="$PWD/utils/three-global-shim.js"
DESTDIR=scripts/external/three

WORKDIR=$(mktemp -d -t three-addons.XXXXXX)
trap 'rm -rf -- "$WORKDIR"' EXIT

for ENTRY in utils/addon-entries/*.js; do
  NAME=$(basename "$ENTRY" .js)
  node_modules/.bin/esbuild "$ENTRY" \
    --bundle --format=iife --target=es2019 \
    --alias:three="$SHIM" \
    --define:import.meta.url="'file:///three-addons/'" \
    --banner:js="/* $NAME addon bundle for three@${THREEVER} — generated by utils/build-addons.sh, do not edit by hand */" \
    --outfile="$WORKDIR/$NAME.js"
  # Content-write in place after a successful build (keeps hardlink inodes,
  # never truncates the committed artifact on failure).
  cat "$WORKDIR/$NAME.js" > "$DESTDIR/$NAME.js"
  echo "updated $DESTDIR/$NAME.js"
done
