#!/bin/bash
# Regenerates the vendored three.js prebundle from the npm ESM build, with
# our local patches applied (see utils/patches/three.module.js.patch).
# Run manually when upgrading three (npm run build:three). The generated
# artifact is committed, so consumers never need three or esbuild installed.
set -e
cd "$(dirname "$0")/.."
REPO=$(pwd)

THREEVER=$(node -pe "JSON.parse(require('fs').readFileSync('node_modules/three/package.json', 'utf8')).version")
DEST=scripts/external/three/three.js

WORKDIR=$(mktemp -d -t three-build.XXXXXX)
trap 'rm -rf -- "$WORKDIR"' EXIT

# Apply local patches to a copy of the ESM build. If a hunk fails after a
# version bump, patch exits nonzero — resolve the conflict and refresh the
# patch file rather than shipping an unpatched build.
cp utils/three-entry.js "$WORKDIR/"
cp node_modules/three/build/three.module.js "$WORKDIR/"
patch --silent "$WORKDIR/three.module.js" < utils/patches/three.module.js.patch

# Bundle from inside the work dir so the source paths esbuild embeds as
# comments are stable relative names, keeping the output deterministic
# (no random temp-dir path baked into the artifact).
(cd "$WORKDIR" && "$REPO/node_modules/.bin/esbuild" three-entry.js \
  --bundle --format=iife --target=es2019 \
  --alias:three=./three.module.js \
  --banner:js="/* three@${THREEVER} prebundle (patched, see utils/patches/) — generated by utils/build-three.sh, do not edit by hand */" \
  --outfile=three.iife.js)

# Content-write over the existing file (keeps the inode, so dev setups that
# hardlink this tree — e.g. janusweb's cp -al layout — see the update in every
# linked copy), and only after esbuild has fully succeeded: a failed build
# never truncates the committed artifact.
cat "$WORKDIR/three.iife.js" > "$DEST"

echo "updated $DEST (three@${THREEVER} + local patches)"
